language: java
jdk:
  - oraclejdk8

script:
 - mvn jacoco:report
 - sudo curl https://www.jpm4j.org/install/script | sudo sh
 - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
 - export CODACY_PROJECT_TOKEN=$projectToken
 - codacy-coverage-reporter -l Java -r coverage.xml